"""Coveo/Salesforce API extraction helpers for Columbia.

Login still happens through the UI in src.columbia.auth. These helpers run only
after an authenticated Playwright page exists.
"""

from __future__ import annotations

import logging
import json
import re
import time
from urllib.parse import urlparse

from src.columbia.auth import get_base_url, get_start_url
from src.columbia.client import ColumbiaAuthExpiredError

logger = logging.getLogger(__name__)

COVEO_SEARCH_URL = "https://columbiauniversityalumniportal.org.coveo.com/rest/search/v2"
COVEO_SEARCH_HUB = "ACAlum"
COVEO_TAB = "All"
COVEO_CQ = (
    '(@objecttype==(User) @sfcontactis_alum__c==True '
    '@sfsearch_visibility__c=="Visible in search results" @SfIsActive==True)'
)
COVEO_FIELDS_TO_INCLUDE = [
    "sfname",
    "sftalkingabout",
    "objecttype",
    "filetype",
    "outlookformacuri",
    "outlookuri",
    "connectortype",
    "urihash",
    "collection",
    "source",
    "author",
    "sfid",
    "sfcreatedbyname",
    "sfcreateddate",
    "sfsmallphotourl",
    "sfcreatedbysmallphotourl",
    "sflastactivitydate",
    "worktitle",
    "sfemail",
    "sfcontactphone",
    "sfbillingcountry",
    "sfbillingcity",
    "sfmailingcountry",
    "sfmailingcity",
    "sffoldername",
    "sfprofile_photo_url__c",
    "sfbadge__c",
    "sfheadline__c",
    "sflocation_city_c__c",
    "sflocation_state__c",
    "sflocation_country__c",
    "date",
    "sfownername",
    "sfaccountname",
    "sfstatus",
    "language",
    "permanentid",
    "fullname",
    "sfprofile_completion__c",
    "sfjob_title__c",
    "sfindustry__c",
    "sfcontactemployer__c",
    "sfemployer_name__c",
    "sfabout_me__c",
    "sfeducation__rinstitution_name__c",
    "sfaffiliations__rrelated_organization_name__c",
    "sfcreatedbyprofile_photo_url__c",
    "sfalumni_education__rschool__c",
    "sfalumni_education__rschool_code__c",
    "sfeducation__rdescriptor__c",
    "sflinkedin_profile_link__c",
    "sflinkedin_profile_url__c",
    "sflinkedin_url_updated__c",
    "sflinkedin_visibility__c",
    "sfsocial_links_private__c",
    "sfsocial_media_account_visibility__c",
]
COVEO_GROUP_BY = [
    "@sfeducation__rschool__c",
    "@sfeducation__rdegree_year__c",
    "@sflocation_country__c",
    "@sflocation_state__c",
    "@sflocation_city_c__c",
    "@sfaffiliations__rrelated_organization_name__c",
    "@sfaffiliations__rfield_of_work__c",
    "@sfaffiliations__rjob_title__c",
]

_CAPTURED_COVEO_HEADERS: dict[str, str] | None = None
_CAPTURED_COVEO_PAYLOAD: dict | None = None
SALESFORCE_API_VERSION = "v66.0"
LINKEDIN_FIELD_NAMES = (
    "LinkedIn_Profile_URL__c",
    "LinkedIn_Profile_Link__c",
    "LinkedIn_Visibility__c",
    "LinkedIn_URL_Updated__c",
    "Social_Links_Private__c",
    "Social_Media_Account_Visibility__c",
)


def coveo_search(
    page,
    first_result: int = 0,
    number_of_results: int = 100,
    query: str = "",
    max_retries: int = 2,
) -> dict | None:
    """Call Columbia's Coveo search endpoint from the authenticated browser.

    The first attempt uses ordinary in-page fetch. If the site requires Coveo
    request headers generated by the UI, we capture one real UI search request
    and reuse only the safe API headers in memory.
    """

    payload = build_coveo_search_payload(
        first_result=first_result,
        number_of_results=number_of_results,
        query=query,
    )
    headers = {"content-type": "application/json", "accept": "application/json"}
    global _CAPTURED_COVEO_HEADERS, _CAPTURED_COVEO_PAYLOAD
    if _CAPTURED_COVEO_HEADERS:
        headers.update(_CAPTURED_COVEO_HEADERS)

    for attempt in range(1, max_retries + 1):
        result = _post_json(page, COVEO_SEARCH_URL, payload, headers)
        if result and not result.get("_error"):
            return result

        status = result.get("status") if isinstance(result, dict) else None
        if status in {401, 403, 419}:
            if not _CAPTURED_COVEO_HEADERS:
                logger.info("Capturing Columbia Coveo headers from the rendered search UI.")
                _CAPTURED_COVEO_HEADERS, _CAPTURED_COVEO_PAYLOAD = _capture_coveo_request(page)
                if _CAPTURED_COVEO_HEADERS:
                    headers.update(_CAPTURED_COVEO_HEADERS)
                    payload = build_coveo_search_payload(
                        first_result=first_result,
                        number_of_results=number_of_results,
                        query=query,
                    )
                    continue
            raise ColumbiaAuthExpiredError(f"Columbia Coveo search returned auth status {status}")

        logger.warning("Columbia Coveo search failed on attempt %s: %s", attempt, _safe_error(result))
        if attempt < max_retries:
            time.sleep(2 ** attempt)

    return None


def build_coveo_search_payload(
    first_result: int,
    number_of_results: int,
    query: str = "",
) -> dict:
    number_of_results = max(1, min(int(number_of_results), 100))
    if _CAPTURED_COVEO_PAYLOAD:
        payload = dict(_CAPTURED_COVEO_PAYLOAD)
        payload["q"] = query
        payload["firstResult"] = max(0, int(first_result))
        payload["numberOfResults"] = number_of_results
        payload["sortCriteria"] = payload.get("sortCriteria") or "relevancy"
        existing_fields = payload.get("fieldsToInclude") or []
        payload["fieldsToInclude"] = _unique_values(
            list(existing_fields) + COVEO_FIELDS_TO_INCLUDE
        )
        payload["allowQueriesWithoutKeywords"] = True
        return payload

    return {
        "q": query,
        "cq": COVEO_CQ,
        "searchHub": COVEO_SEARCH_HUB,
        "tab": COVEO_TAB,
        "locale": "en",
        "wildcards": True,
        "questionMark": True,
        "lowercaseOperators": True,
        "partialMatch": True,
        "partialMatchKeywords": 5,
        "partialMatchThreshold": "50%",
        "firstResult": max(0, int(first_result)),
        "numberOfResults": number_of_results,
        "excerptLength": 200,
        "fieldsToInclude": COVEO_FIELDS_TO_INCLUDE,
        "enableDidYouMean": True,
        "sortCriteria": "relevancy",
        "queryFunctions": [],
        "rankingFunctions": [],
        "groupBy": [
            {
                "field": field,
                "maximumNumberOfValues": 6,
                "sortCriteria": "occurrences",
                "injectionDepth": 1000,
                "completeFacetWithStandardValues": True,
                "allowedValues": [],
            }
            for field in COVEO_GROUP_BY
        ],
        "facetOptions": {},
        "categoryFacets": [],
        "retrieveFirstSentences": True,
        "timezone": "America/New_York",
        "enableQuerySyntax": True,
        "enableDuplicateFiltering": False,
        "enableCollaborativeRating": False,
        "debug": False,
        "allowQueriesWithoutKeywords": True,
    }


def extract_coveo_rows(payload: dict, source_page: int, per_page: int) -> list[dict]:
    rows = []
    for index, result in enumerate(payload.get("results") or []):
        raw = result.get("raw") if isinstance(result.get("raw"), dict) else {}
        row = normalize_coveo_result(result, raw)
        if not row.get("full_name"):
            continue
        row["source_page"] = source_page
        row["source_index"] = ((source_page - 1) * per_page) + index
        row["result_page_url"] = _result_page_url(row["source_index"])
        row["extraction_method"] = "coveo_api"
        rows.append(row)
    return rows


def normalize_coveo_result(result: dict, raw: dict) -> dict:
    sfid = _first_value(raw.get("sfid") or raw.get("syssfid")) or _sfid_from_result(result)
    permanent_id = _first_value(raw.get("permanentid"))
    full_name = _first_value(raw.get("sfname") or raw.get("fullname")) or result.get("title") or result.get("Title")
    badges = _as_list(raw.get("sfbadge__c"))
    class_tag = " ".join(str(item).strip() for item in badges if str(item).strip())
    profile_url = _community_profile_url(sfid)

    row = {
        "source": "columbia",
        "external_id": str(sfid or permanent_id or result.get("uniqueId") or result.get("UniqueId") or ""),
        "salesforce_user_id": str(sfid or ""),
        "permanent_id": str(permanent_id or ""),
        "full_name": str(full_name or "").strip(),
        "class_tag": class_tag,
        "raw_text": "".join(part for part in (str(full_name or ""), class_tag) if part),
        "profile_url": profile_url,
        "coveo_click_uri": result.get("clickUri") or result.get("ClickUri") or "",
        "coveo_printable_uri": result.get("printableUri") or result.get("PrintableUri") or "",
        "email": _first_value(raw.get("sfemail") or raw.get("syssfemail")),
        "phone": _first_value(raw.get("sfcontactphone")),
        "current_title": _first_value(raw.get("sfjob_title__c") or raw.get("worktitle")),
        "current_company": _first_value(raw.get("sfemployer_name__c") or raw.get("sfcontactemployer__c")),
        "industry": _first_value(raw.get("sfindustry__c")),
        "headline": _first_value(raw.get("sfheadline__c")),
        "about_me": _first_value(raw.get("sfabout_me__c")),
        "city": _first_value(raw.get("sflocation_city_c__c") or raw.get("sfmailingcity") or raw.get("sfbillingcity")),
        "state": _first_value(raw.get("sflocation_state__c")),
        "country": _first_value(raw.get("sflocation_country__c") or raw.get("sfmailingcountry") or raw.get("sfbillingcountry")),
        "school": _first_value(raw.get("sfalumni_education__rschool__c") or raw.get("sfeducation__rinstitution_name__c")),
        "school_code": _first_value(raw.get("sfalumni_education__rschool_code__c")),
        "education_descriptor": _first_value(raw.get("sfeducation__rdescriptor__c")),
        "affiliation_organization": _first_value(raw.get("sfaffiliations__rrelated_organization_name__c")),
        "profile_photo_url": _first_value(raw.get("sfprofile_photo_url__c") or raw.get("sfsmallphotourl")),
        "linkedin_profile_url": _personal_linkedin_url(
            _first_value(
                raw.get("sflinkedin_profile_url__c")
                or raw.get("sflinkedin_profile_link__c")
                or raw.get("linkedin_profile_url__c")
                or raw.get("linkedin_profile_link__c")
            )
        ),
        "linkedin_visibility": _first_value(
            raw.get("sflinkedin_visibility__c") or raw.get("linkedin_visibility__c")
        ),
    }
    for key, value in raw.items():
        flat_value = _flatten_value(value)
        if flat_value not in ("", None):
            row[f"coveo_raw_{key}"] = flat_value
    return {key: value for key, value in row.items() if value not in ("", None, [])}


def fetch_salesforce_user_fields(page, user_id: str) -> dict | None:
    """Fetch LinkedIn/social fields from Salesforce UI API for one User record."""
    if not user_id:
        return None
    fields = ",".join(f"User.{name}" for name in LINKEDIN_FIELD_NAMES)
    url = (
        f"{get_base_url()}/services/data/{SALESFORCE_API_VERSION}/ui-api/records/"
        f"{user_id}?optionalFields={fields}"
    )
    return page.evaluate(
        """async (url) => {
            try {
                const resp = await fetch(url, {
                    method: 'GET',
                    credentials: 'include',
                    headers: {
                        'accept': 'application/json',
                        'x-requested-with': 'XMLHttpRequest',
                    },
                });
                const text = await resp.text();
                if (!resp.ok) {
                    return {_error: true, status: resp.status, body: text.slice(0, 500)};
                }
                try {
                    return JSON.parse(text);
                } catch (e) {
                    return {_error: true, status: resp.status, message: String(e), body: text.slice(0, 500)};
                }
            } catch (e) {
                return {_error: true, message: String(e)};
            }
        }""",
        url,
    )


def extract_linkedin_from_salesforce_fields(payload: dict | None) -> dict:
    """Return normalized LinkedIn fields from a Salesforce UI API record payload."""
    if not isinstance(payload, dict) or payload.get("_error"):
        return {}
    fields = payload.get("fields")
    if not isinstance(fields, dict):
        return {}

    def field_value(name: str) -> str:
        item = fields.get(name)
        if not isinstance(item, dict):
            return ""
        value = item.get("displayValue") or item.get("value")
        return str(value).strip() if value not in (None, "") else ""

    linkedin_url = _personal_linkedin_url(
        field_value("LinkedIn_Profile_URL__c")
        or field_value("LinkedIn_Profile_Link__c")
    )
    result = {
        "linkedin_profile_url": linkedin_url,
        "linkedin_visibility": field_value("LinkedIn_Visibility__c"),
        "linkedin_url_updated": field_value("LinkedIn_URL_Updated__c"),
        "social_links_private": field_value("Social_Links_Private__c"),
        "social_media_account_visibility": field_value("Social_Media_Account_Visibility__c"),
    }
    return {key: value for key, value in result.items() if value}


def total_count(payload: dict) -> int | None:
    for key in ("totalCountFiltered", "totalCount"):
        value = payload.get(key)
        if value is not None:
            try:
                return int(value)
            except (TypeError, ValueError):
                pass
    return None


def _post_json(page, url: str, payload: dict, headers: dict) -> dict | None:
    return page.evaluate(
        """async ({url, payload, headers}) => {
            try {
                const resp = await fetch(url, {
                    method: 'POST',
                    credentials: 'include',
                    headers,
                    body: JSON.stringify(payload),
                });
                const text = await resp.text();
                if (!resp.ok) {
                    return {_error: true, status: resp.status, body: text.slice(0, 500)};
                }
                try {
                    return JSON.parse(text);
                } catch (e) {
                    return {_error: true, status: resp.status, message: String(e), body: text.slice(0, 500)};
                }
            } catch (e) {
                return {_error: true, message: String(e)};
            }
        }""",
        {"url": url, "payload": payload, "headers": headers},
    )


def _capture_coveo_request(page) -> tuple[dict[str, str], dict | None]:
    captured: list[tuple[dict[str, str], dict | None]] = []

    def on_request(request):
        if "/rest/search/v2" not in request.url:
            return
        headers = request.headers
        safe_headers = {}
        for name in ("authorization",):
            value = headers.get(name)
            if value:
                safe_headers[name] = value
        payload = None
        post_data = request.post_data
        if post_data:
            try:
                payload = json.loads(post_data)
            except Exception:
                payload = None
        if safe_headers.get("authorization"):
            captured.append((safe_headers, payload))

    context = page.context
    context.on("request", on_request)
    try:
        page.goto(get_start_url(), wait_until="domcontentloaded", timeout=30000)
        _wait_for_coveo_capture(captured, timeout_seconds=8)
        if not captured:
            _trigger_rendered_search(page)
            _wait_for_coveo_capture(captured, timeout_seconds=12)
    finally:
        try:
            context.remove_listener("request", on_request)
        except Exception:
            pass
    if captured:
        logger.info("Captured Columbia Coveo authorization header and payload from rendered UI request.")
        return captured[-1]
    logger.warning("Could not capture Columbia Coveo authorization header from rendered UI.")
    return {}, None


def _wait_for_coveo_capture(captured: list[dict], timeout_seconds: int) -> None:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline and not captured:
        time.sleep(0.25)


def _trigger_rendered_search(page) -> None:
    """Nudge Salesforce search UI to emit a real Coveo request for header capture."""
    try:
        search_box = page.get_by_placeholder("Search your community").first
        search_box.click(timeout=3000)
        search_box.fill("smith", timeout=3000)
        page.keyboard.press("Enter")
        return
    except Exception:
        pass

    try:
        page.evaluate(
            """() => {
                const inputs = Array.from(document.querySelectorAll('input'));
                const input = inputs.find((node) => {
                    const label = [
                        node.getAttribute('placeholder') || '',
                        node.getAttribute('aria-label') || '',
                        node.name || '',
                    ].join(' ').toLowerCase();
                    return label.includes('search');
                });
                if (!input) return false;
                input.focus();
                input.value = 'smith';
                input.dispatchEvent(new Event('input', {bubbles: true}));
                input.dispatchEvent(new Event('change', {bubbles: true}));
                input.dispatchEvent(new KeyboardEvent('keydown', {
                    key: 'Enter',
                    code: 'Enter',
                    keyCode: 13,
                    which: 13,
                    bubbles: true
                }));
                return true;
            }"""
        )
    except Exception:
        pass


def _result_page_url(first_result: int) -> str:
    return f"{get_start_url()}&firstResult={max(0, first_result)}"


def _community_profile_url(sfid: str | None) -> str:
    if not sfid:
        return ""
    return f"{get_base_url()}/s/profile/{sfid}"


def _personal_linkedin_url(url: str | None) -> str:
    if not url:
        return ""
    value = str(url).strip()
    if value.startswith("www."):
        value = f"https://{value}"
    try:
        parsed = urlparse(value)
    except Exception:
        return ""
    host = parsed.hostname.lower().removeprefix("www.") if parsed.hostname else ""
    if not host.endswith("linkedin.com"):
        return ""
    if not parsed.path.lower().startswith("/in/"):
        return ""
    return value


def _sfid_from_result(result: dict) -> str:
    text = " ".join(
        str(result.get(key) or "")
        for key in ("uri", "Uri", "printableUri", "PrintableUri", "clickUri", "ClickUri")
    )
    match = re.search(r"record:([A-Za-z0-9]{15,18})|/([A-Za-z0-9]{15,18})(?:$|[/?#])", text)
    if not match:
        return ""
    return match.group(1) or match.group(2) or ""


def _first_value(value) -> str:
    values = _as_list(value)
    if not values:
        return ""
    return str(values[0]).strip()


def _as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, list):
        return value
    return [value]


def _flatten_value(value) -> str:
    if isinstance(value, list):
        return " | ".join(str(item).strip() for item in value if str(item).strip())
    if isinstance(value, dict):
        return str(value)
    return str(value).strip() if value is not None else ""


def _safe_error(result: dict | None) -> str:
    if not isinstance(result, dict):
        return "no response"
    return str(result.get("status") or result.get("message") or result.get("body") or "unknown")


def _unique_values(values: list) -> list:
    seen = set()
    result = []
    for value in values:
        key = str(value)
        if key in seen:
            continue
        seen.add(key)
        result.append(value)
    return result
